---
- hosts: all
  gather_facts: yes
  tasks:
    - name: remove files
      file:
        state: absent
        src: "{{ ansible_user_dir }}/git/shell-setup/files/{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item }}"
        owner: "{{ ansible_user_id }}"
        backup: yes
      with_items:
        - .bashrc
        - .bash_profile
        - .bash_login
        - .profile
        - .emacs
        - .emacs.d

    - name: create symlinks
      file:
        state: link
        src: "{{ ansible_user_dir }}/git/shell-setup/files/{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item }}"
        owner: "{{ ansible_user_id }}"
        backup: yes
      with_items:
        - .bashrc
        - .profile
        - .emacs
        - .emacs.d

#    - name: synchronize directories
#      copy:
#        src: "files/{{ item }}/"
#        dest: "{{ ansible_user_dir }}/{{ item }}/"
#      with_items:
#        - .emacs.d
        
    - name: create symlink
      file:
        path: "{{ ansible_user_dir }}/.bash_profile"
        state: link
        src: "{{ ansible_user_dir }}/.profile"
        owner: "{{ ansible_user_id }}"
        backup: yes

        
      